export const AUTH_WINDOW_CONTENT_WIDTH = 600;
export const AUTH_WINDOW_CONTENT_HEIGHT = 640;
export const CUSTOM_WINDOW_TITLE_BAR_HEIGHT = 34;
export const CUSTOM_WINDOW_BORDER_WIDTH = 1;

export const WINDOW_TITLE_BAR_CONTROL_WIDTH = 46;
export const WINDOW_TITLE_BAR_TRANSITION_DURATION_MS = 200;
