name: build-mac

on:
  workflow_dispatch:

jobs:
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.21.0
          cache: yarn
      - uses: dtolnay/rust-toolchain@stable
      - run: yarn install --frozen-lockfile
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: pip install -r requirements.txt
      - run: yarn build:mac
      - uses: actions/upload-artifact@v4
        with:
          name: dmg
          path: dist/*.dmg
